name: "Deploy"
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - name: lint
        run: git ls-files *.nix | xargs nix run nixpkgs#nixpkgs-fmt -- --check
      - name: update sources
        run: |
          nix shell nixpkgs#curl nixpkgs#jq -c ./pkgs/dart/update.sh
          rm flake.lock && nix flake update
      - name: test
        run: nix flake check
      - name: push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          tag="$(date --utc --iso-8601)"
          git commit -m "Repo update: $tag" || exit 0
          git tag --annotate --message="Version $tag" "$tag"
          git push --follow-tags origin main
      - uses: cachix/cachix-action@v8
        with:
          name: nix-dart-pub
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: cachix
        run: nix flake archive
